files:
  - source: /src/Bannerlord.BUTRLoader.LauncherEx/Resources/Localization/EN/*.xml
    translation: /src/Bannerlord.BUTRLoader.LauncherEx/Resources/Localization/%two_letters_code%/%original_file_name%
    content_segmentation: 0
    translatable_elements:
      - '/LanguageData[@id],/LanguageData[@name],/LanguageData[@subtitle_extension],/LanguageData[@supported_iso],/LanguageData/strings/string[@text]'
