name: Publish

on:
  push:
    tags:
    - '*'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  #
  MIN_VERSION: 'e1.5.0'

jobs:
  build-module:
    name: Build for NexusMods
    runs-on: windows-2022
    steps:
    - name: Setup
      uses: butr/actions-common-setup@v2.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Download DepotDownloader_2.4.5
      uses: i3h/download-release-asset@v1
      with:
        owner: SteamRE
        repo: DepotDownloader
        tag: DepotDownloader_2.4.5
        file: depotdownloader-2.4.5.zip

    - name: Extract DepotDownloader_2.4.5
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: depotdownloader-2.4.5.zip
        pathTarget: depotdownloader

    - name: Download Bannerlord binaries
      run: >-
        dotnet depotdownloader/DepotDownloader.dll -app 261550 -depot 261551 -beta $env:MIN_VERSION -username ${{secrets.STEAM_LOGIN}}
        -password ${{secrets.STEAM_PASSWORD}} -filelist ./.github/resources/FileFilters.regexp -dir bannerlord
      shell: pwsh

    - name: Build
      run: >-
          $game_version=$env:MIN_VERSION;
          $game_version=$game_version.substring(1);
          dotnet restore src/Bannerlord.BUTRLoader/Bannerlord.BUTRLoader.csproj;
          msbuild src/Bannerlord.BUTRLoader/Bannerlord.BUTRLoader.csproj /p:configuration=Release -p:GameVersion=$game_version /p:GameFolder="$PWD/bannerlord";
      shell: pwsh

    - name: Cleanup
      run: >-
          cd $PWD/bannerlord;
          Get-ChildItem -Exclude bin | Remove-Item -Recurse -Force;
          cd bin;
          cd Win64_Shipping_Client;
          Get-ChildItem -Exclude Bannerlord.BUTRLoader.dll,Bannerlord.BUTRLoader.pdb,Bannerlord.BUTRLoader.LauncherEx.dll,Bannerlord.BUTRLoader.LauncherEx.pdb,TaleWorlds.MountAndBlade.Launcher.exe.config | Remove-Item -Recurse -Force;
      shell: pwsh

    - name: Upload Bannerlord folder
      uses: actions/upload-artifact@v2
      with:
        name: bannerlord
        path: ./bannerlord/

###########################
#          NEXUS          #
###########################

###########################
#         GITHUB          #
###########################
  publish-on-github:
    name: Publish on GitHub
    runs-on: ubuntu-latest
    needs: ["build-module"]
    steps:
    - name: Setup
      uses: butr/actions-common-setup@v2.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}

    - name: Download bannerlord folder
      uses: actions/download-artifact@v3
      with:
        name: bannerlord
        path: ./bannerlord

    - name: Zip Bannerlord.BUTRLoader
      run: 7z a -t7z Bannerlord.BUTRLoader.7z ./bannerlord/*
      #shell: pwsh
      # pwsh casues it to include the root folder

    - name: Install Bannerlord.ChangelogParser
      run: >-
        dotnet tool install -g Bannerlord.ChangelogParser;
      shell: pwsh

    - name: Run ChangelogParser
      id: changelog
      run: |
        vers="$(bannerlord_changelog_parser latestversion -f "$PWD/changelog.txt")"
        echo "::set-output name=mod_version::$vers"
        desc="$(bannerlord_changelog_parser fulldescription -f "$PWD/changelog.txt")"
        desc="${desc//'%'/'%25'}"
        desc="${desc//$'\n'/'%0A'}"
        desc="${desc//$'\r'/'%0D'}"
        echo "::set-output name=mod_description::$desc"


    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: v${{steps.changelog.outputs.mod_version}}
        release_name: Release ${{steps.changelog.outputs.mod_version}}
        body: ${{steps.changelog.outputs.mod_description}}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: ./Bannerlord.BUTRLoader.7z
        asset_name: Bannerlord.BUTRLoader.7z
        asset_content_type: application/x-7z-compressed
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
