name: Test

on:
  repository_dispatch:
    types:
      # If a new version of the game is released, test the repo against it.
      # This way we will always know if the repo is broken on a new update.
      - game_version_update
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'
  pull_request:
    branches:
      - master
    # will be triggered when undrafting or requesting review
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Download DepotDownloader_2.3.6
      uses: i3h/download-release-asset@v1
      with:
        owner: SteamRE
        repo: DepotDownloader
        tag: DepotDownloader_2.3.6
        file: depotdownloader-2.3.6.zip

    - name: Extract DepotDownloader_2.3.6
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: depotdownloader-2.3.6.zip
        pathTarget: depotdownloader

    - name: Download Bannerlord binaries
      run: >-
        dotnet depotdownloader/DepotDownloader.dll -app 261550 -depot 261551 -beta e1.4.3 -username ${{secrets.STEAM_LOGIN}}
        -password ${{secrets.STEAM_PASSWORD}} -filelist ./.github/resources/FileFilters.regexp -dir bannerlord
      shell: pwsh

    - name: Test
      run: >-
          $stable_game_version=$env:STABLE_VERSION;
          $stable_game_version=$stable_game_version.substring(1);
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Debug -p:GameVersion=$stable_game_version -p:GameFolder="$PWD/bannerlord";
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Release -p:GameVersion=$stable_game_version -p:GameFolder="$PWD/bannerlord";
          $beta_game_version=$env:BETA_VERSION;
          $beta_game_version=$beta_game_version.substring(1);
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Debug -p:GameVersion=$beta_game_version -p:GameFolder="$PWD/bannerlord";
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Release -p:GameVersion=$beta_game_version -p:GameFolder="$PWD/bannerlord";
      env:
        STABLE_VERSION: ${{secrets.SYNCED_GAME_STABLE_VERSION}}
        BETA_VERSION: ${{secrets.SYNCED_GAME_BETA_VERSION}}
      shell: pwsh
