name: Test

on:
  repository_dispatch:
    types: [game_version_update, game_version_update_patch]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'
      - 'tests/**'
  pull_request:
    branches:
      - master
    # will be triggered when undrafting or requesting review
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'
      - 'tests/**'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  #
  MIN_VERSION: 'v1.0.0'

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Tests Setup
      uses: butr/actions-tests-setup@v1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        steam-login: ${{secrets.STEAM_LOGIN}}
        steam-password: ${{secrets.STEAM_PASSWORD}}
        stable-version: ${{secrets.SYNCED_GAME_STABLE_VERSION}}

    - name: Test
      run: >-
          $game_version=$env:MIN_VERSION;
          $game_version=$game_version.substring(1);
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Debug -p:GameVersion=$game_version -p:GameFolder="$PWD/bannerlord";
          dotnet test tests/Bannerlord.BUTRLoader.Tests/Bannerlord.BUTRLoader.Tests.csproj --configuration Release -p:GameVersion=$game_version -p:GameFolder="$PWD/bannerlord";
      shell: pwsh